language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.3
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
before_script:
  - ls -la $ANDROID_HOME
script:
  - ./gradlew build
after_success:
  - ls -l app/build/outputs/apk
  - mv app/build/outputs/apk/app-release.apk kaltura-device-info-release.apk
deploy:
  provider: releases
  draft: false
  skip_cleanup: true
  file:
    - kaltura-device-info-release.apk
  on:
    tags: true
  api-key: $GH_TOKEN
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
    on_success: always
    on_failure: always
